Dr/iota typing
uqbar-dao/ziggurat pull request #100
Opened 2022-07-19 22:31 UTC by dr-frmr

2022-07-23 23:09 UTC, ynx0 commented
The one thing that jumps out to me, especially considering the imminent freezing of smart (and likely cooling of other parts of the system) is that arguments in `yolk` are still `ream`ed by mill without any `map` or `set` constructor arms available.

Creating these without `malt`/`silt` or `gas:by`/`gas:in` seem like they would be error prone and poor UX.

I think now that the types are quite restricted, it makes sense to include some facility (i.e. bringing them into the subject thru smart.hoon) to easily construct maps and sets, which would otherwise have to be done manually through nock-js or something.

2022-07-25 00:04 UTC, dr-frmr commented
> arguments in yolk are still reamed by mill without any map or set constructor arms available.

It's not in `mill` that this issue occurs but rather with the wallet app, right? Once it's inside Hoon the action is just a noun and can be constructed with those constructors.

I thought we solved the wallet issue by doing this: `q:(slap !>(+:(cue q.q.smart-lib)) (ream yolk.act))`
I agree that's not *great*, but it doesn't actually touch the execution engine so we can continue to iterate on that.

2022-07-25 13:44 UTC, ynx0 commented
Understood. I want to run through a use case for this so bear with me here:

Let's say I want to create a multisig with an initial set of members. I would like to do something like:
```hoon
[%submit-custom from to town gas=[1 10.000] action='[%create-multisig thresh=3 members=(silt ~[~zod ~nec ~bus])]'
```

(or maybe `members=[[%set %p] (silt ~[~zod ~nec ~bus])]`? just riffing here)




But unless `silt` is part of smart-lib it looks like that's not really possible. Ditto for `malt`. 
Maybe I'm missing something though.

2022-07-25 15:36 UTC, dr-frmr commented
@ynx0, `malt`, `silt`, and `gas` are all contained in hoon.hoon which is built into smart-lib -- you can do exactly what you have there in your action.

2022-07-25 16:58 UTC, ynx0 commented on lib/zig/contracts/zigs.hoon
> +    =/  receiver  (assert-rice account:sur - `me.cart `to.act)
Bikeshed time!

`assert-rice` is a decent name for this arm but I feel like there could maybe be a better one, since you're not just doing asserts on the rice but also typecasting it and producing the updated rice as well.

The best one I could think of was actually a metaphor: `(husk-rice ...)` or even simply `husk`. It seems evocative enough of what's going on but is also not too precise enough to be disqualified.

(Dis)honorable mentions:
- `pull-rice`
- `get-rice`
- `validate-rice`
- `cast-rice`
- `typed-rice`
- `checked-rice`

Feel free to leave as is though. It's obviously not a dealbreaker.

2022-07-25 19:02 UTC, dr-frmr commented on lib/zig/contracts/zigs.hoon
> +    =/  receiver  (assert-rice account:sur - `me.cart `to.act)
I like `husk` a lot too, will change, thanks

2022-07-25 21:11 UTC, tacryt-socryp requested changes
Structure good, have a few nits and a one actual ask regarding `+mule` flow.

2022-07-25 21:11 UTC, tacryt-socryp commented on app/sequencer.hoon
> +      =+  [%uqbar-write !>([%receipt hash (sign:sig our.bowl now.bowl hash) usig])]
Always cast vases. :)

2022-07-25 21:11 UTC, tacryt-socryp commented on app/uqbar.hoon
> +    [%give %fact path %write-result !>([%rejected src.bowl])]~
Always cast vases.

2022-07-25 21:11 UTC, tacryt-socryp commented on lib/indexer-bowl.hoon
> +    |=  [=yolk:smart]
brackets unnecessary with one arg

2022-07-25 21:11 UTC, tacryt-socryp commented on lib/merk.hoon
> +    (pedersen-hash %gash yux)
won't compile

2022-07-25 21:11 UTC, tacryt-socryp commented on lib/zig/contracts/zigs.hoon
> +        allowances.data.giver  %+  ~(jab by allowances.data.giver)
use queen-side for this jab: https://developers.urbit.org/reference/hoon/style

2022-07-25 21:11 UTC, tacryt-socryp commented on lib/zig/mill.hoon
> +      ?~  gra=(~(get by granary) to.shell.egg)  [~ ~ ~ ~ budget.shell.egg %5]
put the result on next line

2022-07-25 21:11 UTC, tacryt-socryp commented on lib/zig/mill.hoon
> +      ?.  ?=(%| -.u.gra)                    [~ ~ ~ ~ budget.shell.egg %5]
same

2022-07-25 21:11 UTC, tacryt-socryp commented on lib/zig/mill.hoon
> +            :-  (mule |.(;;(chick q:(shut dor %write !>(cart) !>(yolk.egg)))))
Let's switch the testmode flow to use `+mock` and `+ajar` instead of `+mule` and `+shut`. That way we can input our scry function `+search` into both of them so that scry shares semantics across test and real modes!

2022-07-25 21:11 UTC, tacryt-socryp commented on lib/zink/pedersen.hoon
> +    ~&  >>>  "hoon..."
remove

2022-07-25 23:35 UTC, dr-frmr commented
@tacryt-socryp: converted all maps that operate inside mill to merkle. Then went through and converted uses of those merkle trees throughout the codebase. Ran some tests through mill and it all works! I think it's time to get a fresh hash-cache.noun so we can run zebra at speed.

2022-07-25 23:42 UTC, dr-frmr commented
Swapped in `husk` for `assert-rice` @ynx0

2022-07-25 23:47 UTC, ynx0 commented
> wheat now store two maps of @tas to lump -- make sure to generate these when you publish a contract or spawn one in an init generator.

Question about this: how would a dev do this in practice? Is it just manually writing out the types or importing them and including them in the wheat? Reason I ask is because it's mentioned but I don't see any tooling to support it and it's unclear exactly what is required.

Ambivalent on whether tooling is necessary before merge, since it seems the important thing is to just freeze smart.hoon.

2022-07-25 23:58 UTC, dr-frmr commented
Jake is working on tooling for lumps. Yeah, we don't actually need the auto-conversion methods right now, but will get them in the next several weeks for sure.

2022-07-26 13:53 UTC, ynx0 commented on app/sequencer.hoon
> +      =/  batch-num  1  ::  TODO
Looks like this todo needs to be done in the current PR.

2022-07-26 17:52 UTC, dr-frmr commented on app/sequencer.hoon
> +      =/  batch-num  1  ::  TODO
true -- added

2022-07-26 18:13 UTC, ynx0 approved these changes

2022-07-26 18:32 UTC, dr-frmr commented
Switching to draft til I get a scry working

2022-07-27 14:38 UTC, ynx0 commented on lib/zig/sys/smart.hoon
> +  .^(grain /granary/id)
This should be `(scot %ux id)` but more importantly I don't think this wrapper arm is necessary yet. `.^` are fine, even from a stylistic point of view imo. 

It seems a bit early to make this wrapper.

2022-07-27 14:44 UTC, tacryt-socryp commented on lib/zig/sys/smart.hoon
> +  .^(grain /granary/id)
I desire the wrapper arm as a means of further documenting the semantics of how we do scries within contracts, and also as an alternative to `.^`.

2022-07-27 16:42 UTC, dr-frmr commented on lib/zig/sys/smart.hoon
> ++$  caller   $@(id account)
We could get rid of the fork entirely. It's sort of a leftover option for when we were considering how to have contracts make calls themselves. It's pretty clear now that we only use the `account` structure

2022-07-27 16:59 UTC, ynx0 commented on lib/zig/sys/smart.hoon
> ++$  caller   $@(id account)
That's what I was hoping for. Sweet.

2022-07-27 23:42 UTC, dr-frmr commented
Scrys are solid. Had to remove `mock` mode from mill due to it not handling scrys correctly (perhaps an issue to bring up sometime).

2022-07-28 13:02 UTC, ynx0 commented on lib/zig/sys/smart.hoon
>    |=  [next=(list [to=id town-id=id args=yolk]) rooster=chick]
```suggestion
++  continuation
  |=  [next=(list [to=id town-id=id =yolk]) rooster=chick]
```

Just to be consistent

2022-07-28 15:08 UTC, dr-frmr commented on lib/zig/sys/smart.hoon
> +  p.grain(data ;;(typ data.p.grain))
We should return all the data, otherwise you have to be repetitive to access certain info. If I can do the first option and it returns a grain that doesn't have to be branched on again to assert it's a rice, I'll switch to that.

2022-07-28 15:30 UTC, dr-frmr commented on lib/zig/sys/smart.hoon
> +  p.grain(data ;;(typ data.p.grain))
Just tried returning a typed grain from `husk`, and it works, but I don't really feel like it's better because you're stuck with the `p` branching -- I kind of prefer getting a rice and just attaching the `each` tag when I want to return it. Since `husk` is only for rice and should crash on wheat I think this is reasonable. Dealing with a grain out of `husk` actually adds a lot of extra characters to a contract..

2022-07-28 15:34 UTC, ynx0 commented on lib/zig/sys/smart.hoon
> +  p.grain(data ;;(typ data.p.grain))
Gotcha

2022-07-28 17:29 UTC, hosted-fornet commented on app/indexer.hoon
> -          grain-eggs-index  (gas-ja-second-order grain-eggs-index grain-eggs town-id)
I'm curious: why was grain-eggs was removed?

2022-07-28 18:10 UTC, dr-frmr commented on app/indexer.hoon
> -          grain-eggs-index  (gas-ja-second-order grain-eggs-index grain-eggs town-id)
Well, eggs no longer contain any grains -- we've changed the old `embryo` structure and replaced all the contract input grain maps with scrying the granary directly.

2022-07-28 18:33 UTC, hosted-fornet commented on app/indexer.hoon
> -          grain-eggs-index  (gas-ja-second-order grain-eggs-index grain-eggs town-id)
Oh, I see. It is probably desirable to have grain-eggs indexed at some point, if possible, but I'm not familiar enough with the zink code and scrying the granary to see how to do it. I'll put it on my todo list for a future PR.

2022-07-28 20:51 UTC, ynx0 commented
One issue that cropped up for me that I thought I should mention to potentially save you the goose chase.

Here is the buggly line: `(husk account:sur giv me.cart id.from.act)`.

Looks fine, but actually it should actually be ``(husk account:sur giv `me.cart `id.from.act)``.

This is because of the way that wet gates work I think. What happens is the error shows up only at the definition of `husk` in smart.hoon and makes it look like it's erroneously defined, with no mention of the faulty callsite anywhere. Kinda cringe.

2022-07-28 21:16 UTC, ynx0 commented on lib/zig/sys/smart.hoon
>  ::
Petition to add `$big` to smart.hoon somewhere. It's needed in places where you are explicitly not using `+result` and are trying to do e.g. `(put:big issued last-grain)` or `(gas:big ...)` etc.
```suggestion
::
++  big  (bi id grain)  ::  merkle engine for granary
```

2022-07-28 22:44 UTC, dr-frmr commented on app/indexer.hoon
> -          grain-eggs-index  (gas-ja-second-order grain-eggs-index grain-eggs town-id)
I think the best way might be to lightly interpret the action contained in the egg and turn any grain-ids inside to links to that grain, could even do purely on frontend potentially.

2022-07-28 22:45 UTC, dr-frmr commented
@ynx0 yes, `husk` takes units for its final two arguments.

2022-07-28 22:46 UTC, dr-frmr commented on lib/zig/sys/smart.hoon
>  ::
@tacryt-socryp does this seem right for pre-including a merkle map engine, or would users be better off making it themselves?

2022-07-28 22:50 UTC, tacryt-socryp commented on lib/zig/sys/smart.hoon
>  ::
Go for it, no harm, and it gives it a canonical name.

2022-07-28 22:52 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +      ::  ignore trace printfs
I was wondering what we'd do about this lol

2022-07-29 18:15 UTC, ynx0 commented on lib/zig/sys/smart.hoon
> +      [%address @ux]  [%grain @ux]
Now that `plant` is gone and grains are scried out from the granary, is the `%grain` case/distinction necessary here?

Similar question wrt `%address`.

2022-07-29 19:15 UTC, dr-frmr commented on lib/zig/sys/smart.hoon
> +      [%address @ux]  [%grain @ux]
They will remain iota types but the [%grain-id] tag that we have in contract actions will go away now that it's not being interpolated.

2022-07-29 22:47 UTC, ynx0 commented on lib/zig/sys/smart.hoon
> +      [%address @ux]  [%grain @ux]
I see. Still wondering why these are necessary instead of just using `%ux`. Like are `%grain` iota validated in some way by checking if they are in the granary or not before executing the contract? Are `%address` iota checked to be valid addresses (or intended to be)?

 A quick search doesn't yield me any usages.

2022-07-29 23:28 UTC, dr-frmr commented
Alright, unfortunately the `husk` wet gate is not functional inside zink. Something about the mold structure being passed around.

2022-07-29 23:38 UTC, ynx0 commented
Sad!

2022-07-30 07:53 UTC, dr-frmr commented on lib/zig/sys/smart.hoon
> +      [%address @ux]  [%grain @ux]
they're not necessary they're just nice to have because these iotas are used to specify contract arguments and it's good to show what that argument is being used for. same reason we alias `@ux` to `id`, `address`, and `hash` in various places.

2022-07-30 23:40 UTC, tacryt-socryp approved these changes
Beautiful. LGTM

2022-07-31 15:39 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +      ?.  ?=((unit) sam)  %|^trace
Not enough... this can still crash if the `unit` is `~`.

2022-08-01 03:18 UTC, dr-frmr commented on lib/zink/zink.hoon
> +      ?.  ?=((unit) sam)  %|^trace
fixed

2022-08-01 03:41 UTC, merged