Refactor indexer+uqbar+wallet to match new types
uqbar-dao/ziggurat pull request #103
Opened 2022-07-25 19:01 UTC by dr-frmr

Indexer should be good
Uqbar.hoon should be good
now for wallet...

2022-08-04 13:19 UTC, ynx0 requested changes

2022-08-04 13:19 UTC, ynx0 commented on app/sequencer.hoon
> +    ?~  typ=(~(get by interface.p.u.g) label)
Looks like this should be `types.p.u.g`

2022-08-04 13:19 UTC, ynx0 commented on lib/indexer.hoon
> +    |=  [=yolk:smart]
Technically wrapping this expr in `[]` is unnecessary, even though tbh I think stylistically I prefer it.

2022-08-04 13:30 UTC, tacryt-socryp commented on lib/indexer.hoon
> +    |=  [=yolk:smart]
I stylistically do not prefer it.

2022-08-04 20:14 UTC, dr-frmr commented on lib/indexer.hoon
> +    |=  [=yolk:smart]
I don't like this either and will remove -- this ends up happening often for me cause I'll refactor an arm to only have 1 input and forget to remove the brackets, and since it doesn't introduce a compile error...

2022-08-04 21:25 UTC, dr-frmr commented
Addressed the review, think we're good

2022-08-05 02:08 UTC, ynx0 approved these changes

2022-08-05 05:29 UTC, merged