fix #193
uqbar-dao/ziggurat pull request #194
Opened 2022-10-11 15:56 UTC by 0x70b1a5

2022-10-11 16:03 UTC, dr-frmr requested changes

2022-10-11 16:03 UTC, dr-frmr commented on app/ziggurat.hoon
> +      =/  data-text  ;;(@t data.rice)
`fry-rice` produces a `@ux`, not a `rice`. So `data.rice` won't work here. You need to still bring in all the rice data via the poke, and produce the ID like you're doing.

2022-10-11 16:03 UTC, dr-frmr commented on app/ziggurat.hoon
> +      =*  rice  (fry-rice:smart lord.act holder.act town.act salt.act)
Same issue here

2022-10-11 16:03 UTC, dr-frmr commented on sur/ziggurat.hoon
> +          [%add-to-state lord=id:smart holder=id:smart town=id:smart salt=@]
The poke is missing some of the fields needed to create a `rice`. There are only the fields needed to generate the hash -- still need `label` and `data`

2022-10-12 15:21 UTC, dr-frmr commented on app/ziggurat.hoon
> +      =/  rice  [salt=salt.act label=label.act data=data.act id=id lord=lord.act holder=holder.act town-id=town-id.act]
Can either break this line into multiple lines (to stay below 80char line width) or preferably remove the assigned faces and instead impose them by doing `=/  =rice  [salt.act label.act data.act id lord.act holder.act town-id.act]`

2022-10-12 15:21 UTC, dr-frmr commented on app/ziggurat.hoon
> +      =.  data.rice
To make this less repetitive, can move these lines above 209 and generate the proper data for the rice there. Can get rid of the `=.` if we just put the output of `text-to-zebra-noun` in the rice to begin with.

2022-10-12 15:21 UTC, dr-frmr commented on mar/ziggurat/contract-action.hoon
> -          [%id (se %ux)]
I just realized that it's possible that this `parse-rice` arm might be used elsewhere to parse rice with IDs. It might make sense to create a variant that still does, while naming this version something like `parse-rice-without-id`

2022-10-12 15:21 UTC, dr-frmr commented on app/ziggurat.hoon
> +      =/  rice  [salt=salt.act label=label.act data=data.act id=id lord=lord.act holder=holder.act town-id=town-id.act]
Same as above re: line width and faces

2022-10-12 15:51 UTC, 0x70b1a5 commented on app/ziggurat.hoon
> +      =.  data.rice
Moving to something like this: 
```hoon
    %add-to-state
      =/  data-text  ;;(@t data.act)
      =/  id  (fry-rice:smart lord.act holder.act town-id.act salt.act)
      =/  rice  :*
          id 
          salt.act 
          lord.act 
          label.act 
          holder.act 
          town-id.act
          data=(text-to-zebra-noun data-text smart-lib-vase)
        ==
```
Do you know if assigning faces is necessary?

2022-10-12 16:46 UTC, dr-frmr commented on app/ziggurat.hoon
> +          ==
Formatting for this should align with standard backstep notation:
```
=/  rice
  :*  salt=salt.act
      label=label.act
      data=data.act
      id=id
      lord=lord.act
      holder=holder.act
      town-id=town-id.act
  ==
```

2022-10-12 16:46 UTC, dr-frmr commented on app/ziggurat.hoon
> +          ==
Can keep the `:*` on the same line as `=/  rice` but then need to indent all the entries in the list to match

2022-10-12 17:30 UTC, dr-frmr approved these changes

2022-10-12 17:30 UTC, dr-frmr commented
Ok looks good!

2022-10-12 17:35 UTC, merged