indexer: index the chain
uqbar-dao/ziggurat pull request #25
Opened 2022-03-23 06:37 UTC by hosted-fornet

Add initial work on a chain indexer agent.

Lots still todo, including:
* Actual indexing in `+on-agent`
* Scrys
* Allow subscriptions

2022-03-25 17:53 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +        [%x %grain @ ~]
Hmm, I hadn't considered a town over time.

Another thing lacking here is retrieval of a set of txs/blocks/towns that are time bounded, e.g., all blocks since yesterday.

2022-03-25 17:59 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +        [%x %grain @ ~]
I wonder it towns should be designated by hashes rather than `@ud` indices. Can a town be shut down? I am imagining a scenario:

* There are two towns, `0` and `1`.
* Town `1` is halted after some number of blocks: now there is just one town.
* After some additional blocks a brand new town is started. It is labeled `1`

The above scenario would make it hard to distinguish between the original town `1` and the new town `1`.

Some alternatives to designating towns by hashes would be somehow tracking the next "available" town `@ud` or tracking the "life" a given town `@ud` is on.

@dr-frmr

2022-03-25 21:46 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +      =index:uqbar-indexer
Didn't know about this pattern, thanks for calling attention to it. Changed in 011038b.

2022-03-25 21:51 UTC, tacryt-socryp commented on app/uqbar-indexer.hoon
> +        [%x %grain @ ~]
We just used `@ud` as a standin. `@ux` is probably better

2022-03-25 22:57 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +      ::     %serve-update
Added back in (commented out) in 34c9e05. Not sure how to communicate the result back to the caller `src.bowl`. One way I could imagine is `poke`ing it back to an agent we know will be running on their ship.

Is there a good way to do this?

2022-03-25 23:19 UTC, hosted-fornet commented
Hmm, need some way that a newly started indexer can get the backlog of blocks in order to serve the complete chain state, preferably without DOSing the validator/indexer that is sending the data.

2022-03-26 02:11 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +  ++  on-watch  on-watch:def
Done in 34c9e05. I added more state to consolidate what, e.g., grains we are publishing about. Not sure if we can do this with the subscriber info that exists in the bowl; if so we may want to remove the additional state I added.

2022-03-26 04:04 UTC, tacryt-socryp commented on app/uqbar-indexer.hoon
> +        =|  cards=(list card)
I recommend making all of these cards using `:~` and `=/` instead of snocing and welding them. Inefficient

2022-03-26 04:04 UTC, tacryt-socryp commented on app/uqbar-indexer.hoon
> +            block-index  block-index
360-364 are redundant with the prior `=:`. I recommend moving the wing modifications in the prior `=:` here.

2022-03-29 00:50 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +        (~(put ju chunk-subs) town-id src.bowl)
23af2ee

2022-03-29 00:50 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +  ++  on-init
9505bd8

2022-03-29 00:50 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +            block-index  block-index
1b41384

2022-03-29 00:50 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +        =|  cards=(list card)
1b41384

2022-03-29 00:50 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +          %+  murn  ~(tap in ~(key by chunk-subs))
1b41384

2022-03-29 00:50 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +        =.  block-index  (~(gas ju block-index) block-hash)
1b41384

2022-03-29 01:15 UTC, tacryt-socryp commented on sur/uqbar-indexer.hoon
>  |%
Strongly recommend that you use an ordered-map instead of a list for log n insertion, deletion, and gets.

2022-03-29 16:37 UTC, hosted-fornet commented on sur/uqbar-indexer.hoon
>  |%
Now using mop in eb1e49e.

2022-03-30 00:40 UTC, hosted-fornet commented
Current TODOs:

1. Subscriptions to validators using validator types. May want to redo some of the types used here and use validator types instead (e.g. the `block-bundle` here and `slot` there are nearly equivalent, so should probably use `slot`).
2. Consume/ingest chunks? It may make more sense to not do this and to instead just consume blocks, but blocks where the `chunks` map is only one (or a subset of) town(s).
3. Work out the `%hash` scry/sub path: get various types playing along together.
4. `%serve-update` poke to allow one-off queries from remote ships.
5. Time bounded queries? E.g., "all transactions involving address `foo` in the past three months". `epoch`s might be useful here.
6. Test!

2022-04-08 17:47 UTC, hosted-fornet commented
Still TODO:

* time-bounded scries
* poke for remote one-time access
* poke for one-time block adds
* fix typing so can return /hash

Some useful commands for testing:

```
:: start chain and indexer
:wallet &zig-wallet-poke [%populate 0xbeef]
:ziggurat &zig-chain-poke [%set-addr 0x2.e3c1.d19b.fd3e.43aa.319c.b816.1c89.37fb.b246.3a65.f84d.8562.155d.6181.8113.c85b]
:ziggurat|start-testnet now
:uqbar-indexer &set-chain-source [our %ziggurat]
:sequencer|init 1

:: send a tx and watch the `/grain` subscription path
:wallet|basic-tx 1 0x3.4cdd.5f53.b551.e62f.2238.6eb3.8abd.3e91.a546.fad3.2940.ff2d.c316.50dd.8d38.e609 777
-zig!watch-indexer /grain/0x10b.4ca5.fb93.480b.a0d7.c168.0f3e.6d43

:: some scries
=ui -build-file /=zig=/sur/uqbar-indexer/hoon
.^((unit update:ui) %gx /=uqbar-indexer=/id/0x2.e3c1.d19b.fd3e.43aa.319c.b816.1c89.37fb.b246.3a65.f84d.8562.155d.6181.8113.c85b/noun)
.^((unit update:ui) %gx /=uqbar-indexer=/to/0x2.e3c1.d19b.fd3e.43aa.319c.b816.1c89.37fb.b246.3a65.f84d.8562.155d.6181.8113.c85b/noun)
.^((unit update:ui) %gx /=uqbar-indexer=/from/0x2.e3c1.d19b.fd3e.43aa.319c.b816.1c89.37fb.b246.3a65.f84d.8562.155d.6181.8113.c85b/noun)
.^((unit update:ui) %gx /=uqbar-indexer=/grain/0x10b.4ca5.fb93.480b.a0d7.c168.0f3e.6d43/noun)
.^((unit update:ui) %gx /=uqbar-indexer=/holder/0x2.e3c1.d19b.fd3e.43aa.319c.b816.1c89.37fb.b246.3a65.f84d.8562.155d.6181.8113.c85b/noun)
.^((unit update:ui) %gx /=uqbar-indexer=/lord/0x656c.6269.676e.7566/noun)
```

2022-04-08 18:08 UTC, tacryt-socryp requested changes
I recommend getting rid of the commented out code and just putting TODOs pointing to the commit hash that still contains it if you think you may need some of it later. Otherwise, happy to chat about how this is structured or any other specific comments I made.

2022-04-08 18:08 UTC, tacryt-socryp commented on app/uqbar-indexer.hoon
> +    %+  murn  updates
Just `+turn` here, if you return empty list `+zing` will get rid of it anyway.

2022-04-08 18:08 UTC, tacryt-socryp commented on app/uqbar-indexer.hoon
> +            (~(uni in grains.u.out) grains.u.next-update)
dedent line twice

2022-04-08 18:08 UTC, tacryt-socryp commented on app/uqbar-indexer.hoon
> +          :_  parsed-grain
Dedent 659-661 twice and put a `::` afterwards that is dedented once further.

2022-04-08 18:08 UTC, tacryt-socryp commented on app/uqbar-indexer.hoon
> +          [[holder-id grain-id] parsed-holder]
same

2022-04-08 18:08 UTC, tacryt-socryp commented on app/uqbar-indexer.hoon
> +          [[lord-id grain-id] parsed-lord]
same

2022-04-08 18:08 UTC, tacryt-socryp commented on app/uqbar-indexer.hoon
> +++  combine-update-sets
For arms only called in one location from the main agent, consider putting them inline with `|^` to clean up the namespace. Generally better for arms to be closer to where they're called than in a jumble with others that are unrelated.

2022-04-08 18:08 UTC, tacryt-socryp commented on app/uqbar-indexer.hoon
> +++  consume-ziggurat-update
Consider moving to `on-agent`

2022-04-08 22:23 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +++  consume-ziggurat-update
Done in 7cdee12

Eventually I may want to add a poke to give a block to the indexer to ingest, and so at that time this will move back into the helper core. I imagine this being used for catchups and initial syncs. I'm not certain this is the right way to do this though: I think Ben has a different catch up method already implemented in ziggurat/sequencer, so I'll check that out before going too far down this route.

2022-04-08 22:23 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +++  combine-update-sets
Done in 8047c84

2022-04-08 22:23 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +          [[lord-id grain-id] parsed-lord]
Dedents in dbc2da7

2022-04-08 22:23 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +          [[holder-id grain-id] parsed-holder]
Dedents in dbc2da7

2022-04-08 22:23 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +          :_  parsed-grain
Dedents in dbc2da7

2022-04-08 22:23 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +            (~(uni in grains.u.out) grains.u.next-update)
Dedents in dbc2da7

2022-04-08 22:23 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +    %+  murn  updates
d8ce49d

2022-04-08 22:24 UTC, hosted-fornet commented on app/uqbar-indexer.hoon
> +      chunk-subs=(jug town-id=@ud sub=@p)
Oof, I was worried about this. I changed to use `sup` in b34806d

2022-04-08 22:25 UTC, hosted-fornet commented
Got rid of TODOs in 730fc33 and addressed other comments as well: thanks for the review. Ready to merge as far as I'm concerned.

2022-04-09 01:36 UTC, merged