Jets
uqbar-dao/ziggurat pull request #37
Opened 2022-04-14 22:20 UTC by martyr-binbex

2022-04-14 22:31 UTC, tacryt-socryp requested changes

2022-04-14 22:31 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    ?+  arm  `app
I wonder if we can make this more elegant by doing something a bit more raw. I need to think about it. It's clear as is, and obviously works though.

2022-04-14 22:31 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    ?@  mjet  `app
Should be `?~` and can be defined inline:

?~  mjet=...

2022-04-14 22:31 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    ?@  sub  `app
Should be ?~

2022-04-14 22:31 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    ?@  arg  `app
Should be ?~

2022-04-14 22:31 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    =^  arg=body  app  ^$(s sub^s, f sam.next)
Style, put the ^$ on the next line

2022-04-14 22:31 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    =^  sub=body  app  ^$(f head)
Style, put the ^$ on next line

2022-04-14 22:31 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    ?@  mj  `app
Use ?~ for matching ~

2022-04-14 22:31 UTC, tacryt-socryp commented on sur/zink.hoon
> ++$  jetmap  (map @ @tas)
Please incorporate a gas cost function in this map that takes in the same input as the target jet and is then run to determine cost.

2022-04-14 22:50 UTC, martyr-binbex commented on lib/zink/zink.hoon
> +    ?@  mj  `app
That requires `?:  ?~(mj) app` which is more verbose

2022-04-14 22:52 UTC, tacryt-socryp commented on lib/zink/zink.hoon
> +    ?@  mj  `app
No, it doesn't. You can drop it in place of your ?@

2022-04-15 03:42 UTC, martyr-binbex commented on lib/zink/zink.hoon
> +    ?@  arg  `app
I realized this line can be deleted since `both` will return ~ if either unit is ~

2022-04-15 15:28 UTC, tacryt-socryp approved these changes
LGTM

2022-04-15 15:40 UTC, merged